### ISSUE TITLE
Aliases when applied to short signals

### ISSUE THREAD

**Issue by dipterix** [preraulab/multitaper_toolbox#1]
Thanks for publishing your amazing work! I'm trying to build a pipeline to switch from wavelet to your multitaper function. Starting with this toy example, there should be constant significant power near 10 Hz and decaying power near 5 Hz. However, I noticed "weird" aliasing in the spectrogram. The code along with my results is attached here. I was wondering if it is normal to see the blue pixels appear periodically.

```r
time <- seq(0, 3, by = 0.01)
x <- sin(time * 20*pi) + exp(-time^2) * cos(time * 10*pi)
multitaper_spectrogram_R(
  x, 100, frequency_range = c(0,15),
  time_bandwidth=1.5,
  window_params=c(1.3,0.01)
)
```

<img width="967" alt="image" src="https://user-images.githubusercontent.com/8163576/137387280-1be1cc22-35ff-4bff-8e21-7a39c3f058a4.png">

Thanks.

**Comment by thpossidente** [comment]
Thank you for your patience with our reply.

This oddity is caused by having such a short segment of nosieless data (3s) being analyzed with a window size that is large relative to the segment, and a very small step size. With such a small step size relative to the low frequency noiseless data, you can see the effects of phase showing up as those little blue ripples.

Using a 60s segment (and therefore adding a longer delay period on the decay of the 5Hz power), 5s window size, 1s step size, and a half-time bandwidth of 2.5, the resulting spectrogram is:
![untitled](https://user-images.githubusercontent.com/21342044/165863184-fd25b313-805d-46cd-800e-64621d82110b.jpg)


A good overview of some of the parameter settings for the multitaper spectrogram can be found [here](https://prerau.bwh.harvard.edu/multitaper/) (the second half of tutorial #2 especially). Additionally, the "parameters" section of the README for the [multitaper_toolbox ](https://github.com/preraulab/multitaper_toolbox) repo may be useful. 

-- Tom P., Prerau Lab Research Assistant
